tags:
  - name: submission
    description: submission API

paths:
  /submitReceipt:
    # [POST] submission
    post:
      tags:
        - submission
      summary: Validate Receipt
      parameters:
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/submitReceipt'
      responses:
        200:
          description: 'Submission response'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  submitReceipt:
    type: object
    required:
      - beforeImage
      - afterImage
    properties:
      beforeImage:
        type: string
        description: Base64 encoded image of the receipt before processing
      afterImage:
        type: string
        description: Base64 encoded image of the receipt after processing
      address:
        type: string
        description: User's address
      deviceID:
        type: string
        description: User's device ID

schemes:
  - https
  - http
